import streamlit as st
import google.generativeai as genai

# Configure Google Generative AI
genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])

# Function to get responses from the Gemini Pro model
model = genai.GenerativeModel("gemini-1.5-flash")

def get_gemini_response(medicine_name):
    if medicine_name:
        question = f"""
        For the medicine: {medicine_name}, briefly explain what it is used for in simple terms that a non-medical person can understand.
        Additionally, provide a summary explaining the likely reason this medicine has been prescribed as part of a treatment plan.
        The goal is to educate the user about their medicine treatment plan without using complex medical terminology.
        Provide the response in {language}
        """
        response = model.generate_content(question)
        return response.text
    else:
        return "Please enter the name of your medicine and relevant information only."

# Initialize Streamlit app
st.set_page_config(page_title="MedExplainer: Your GenAI-Powered Medicine Companion", layout="centered")
st.title("MedExplainer: Your GenAI-Powered Medicine Companion 💊")

# App description
st.markdown("""
Welcome to **MedExplainer**!
This app uses advanced AI to help you understand your prescribed medicines.
Enter the name of your medicine below, and click **Get Explanation**.
""")

# Input box for medicine name
medicine_input = st.text_input("Enter the name of your medicine:", placeholder="e.g., Metformin")

# Input box for preferred language
language_input = st.text_input("Enter your preferred language (default is English):", value="English")

submit = st.button("Get Explanation")

# When submit is clicked
if submit:
    explanation = get_gemini_response(medicine_input)
    st.subheader("Medicine Explanation and Treatment Plan Summary:")
    st.write(explanation)

# Add disclaimer
st.markdown("""
---
**Disclaimer:** This information is generated by a Large Language Model (LLM) and may contain inaccuracies. Always consult and confirm with a certified healthcare professional.
""")
